import { 
  collection, 
  doc, 
  getDocs,
  query,
  where,
  setDoc,
  writeBatch,
  serverTimestamp,
  Timestamp
} from 'firebase/firestore'
import { db } from '@/lib/firebase'
import type { User, Assignment } from '@/types/user'

interface CreateUserPayload {
  id: string // The UID generated by Firebase Auth provisioning
  displayName: string
  email: string
  roles: string[]
  rubricIds?: string[]
  teamIds?: string[]
}

/**
 * 🚀 PROVISION USER: Creates the User document profile and handles 
 * atomic cross-junction generation for assessors inside a single transaction batch.
 */
export async function provisionNewUser(payload: CreateUserPayload): Promise<void> {
  const batch = writeBatch(db)
  
  const userDocRef = doc(db, 'users', payload.id)
  const isAssessor = payload.roles.includes('assessor')

  // 1. Prepare clean base user payload map structure
  const userData: User = {
    id: payload.id,
    displayName: payload.displayName.trim(),
    email: payload.email.trim().toLowerCase(),
    roles: payload.roles as any,
    // Store arrays on the profile for fast local evaluation context checking
    rubricIds: isAssessor ? payload.rubricIds || [] : [],
    teamIds: isAssessor ? payload.teamIds || [] : []
  }

  // Add the user doc creation operation to the atomic pipeline block
  batch.set(userDocRef, userData)

  // 2. Cross-reference assignment records if the user acts as an assessor matrix node
  if (isAssessor && payload.rubricIds && payload.teamIds) {
    const assignmentsCollectionRef = collection(db, 'assignments')

    // Generate a cartesian cross-product junction entry for every rubric-to-team link pair
    payload.rubricIds.forEach((rubricId) => {
      payload.teamIds!.forEach((teamId) => {
        const assignmentDocRef = doc(assignmentsCollectionRef) // Auto-generated UUID
        
        const assignmentData: Assignment = {
          id: assignmentDocRef.id,
          assessorId: payload.id,
          teamId: teamId,
          rubricId: rubricId,
          assignedAt: serverTimestamp() as Timestamp
        }

        batch.set(assignmentDocRef, assignmentData)
      })
    })
  }

  // 3. Commit the entire bundle to Firestore atomically.
  // If one assignment write drops, the user record is safely rolled back.
  await batch.commit()
}

/**
 * 🔄 UPDATE ASSIGNMENTS: Syncs the profile array maps for an existing user.
 * (Note: If you need to completely overwrite junction targets, you can expand this 
 * to wipe old /assignments documents matching the assessorId before appending new ones).
 */
export async function updateAssessorAssignments(
  userId: string,
  rubricIds: string[],
  teamIds: string[]
): Promise<void> {
  try {
    const userDocRef = doc(db, 'users', userId)
    
    await setDoc(userDocRef, {
      rubricIds,
      teamIds
    }, { merge: true })
  } catch (error) {
    console.error(`Failed to re-sync profile arrays for assessor [${userId}]:`, error)
    throw error
  }
}

/**
 * 🔍 READ CONTEXT: Simple snapshot grab to check routing security clearance.
 */
export async function getUserClearanceProfile(userId: string): Promise<User | null> {
  const docRef = doc(db, 'users', userId)
  const snapshot = await getDoc(docRef)
  
  if (!snapshot.exists()) return null
  return snapshot.data() as User
}

/**
 * 🔄 SYNC ASSIGNMENTS: Updates an assessor's profile arrays and completely replaces
 * their junction entries in the /assignments collection to reflect the new state.
 */
export async function syncAssessorAssignments(
  userId: string,
  newRubricIds: string[],
  newTeamIds: string[]
): Promise<void> {
  const batch = writeBatch(db)
  
  // 1. Reference the user document and update their tracking arrays
  const userDocRef = doc(db, 'users', userId)
  batch.update(userDocRef, {
    rubricIds: newRubricIds,
    teamIds: newTeamIds
  })

  try {
    // 2. Query and delete ALL existing junction entries for this assessor
    const assignmentsCollectionRef = collection(db, 'assignments')
    const oldAssignmentsQuery = query(assignmentsCollectionRef, where('assessorId', '==', userId))
    const oldAssignmentsSnapshot = await getDocs(oldAssignmentsQuery)

    oldAssignmentsSnapshot.docs.forEach((doc) => {
      batch.delete(doc.ref)
    })

    // 3. Generate the fresh cross-product junction matrix for the new assignments
    newRubricIds.forEach((rubricId) => {
      newTeamIds.forEach((teamId) => {
        const newAssignmentDocRef = doc(assignmentsCollectionRef) // Generates fresh ID
        
        const assignmentData: Assignment = {
          id: newAssignmentDocRef.id,
          assessorId: userId,
          teamId: teamId,
          rubricId: rubricId,
          assignedAt: serverTimestamp() as Timestamp
        }

        batch.set(newAssignmentDocRef, assignmentData)
      })
    })

    // 4. Commit the batch transaction atomically
    await batch.commit()
    console.log(`Successfully synced all junction targets for Assessor [${userId}].`)
  } catch (error) {
    console.error(`Failed to overwrite assignment junction targets for [${userId}]:`, error)
    throw error
  }
}